// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function FirstRescript(Props) {
  return React.createElement("div", undefined, "Hi there Rescript");
}

var make = FirstRescript;

export {
  make ,
  
}
/* react Not a pure module */
